import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontSize: 10,
        lineHeight: 1.5,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        paddingBottom: 10,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    subtitle: {
        fontSize: 10,
        color: '#6B7280',
    },
    table: {
        display: 'flex',
        width: 'auto',
        borderStyle: 'solid',
        borderRightWidth: 0,
        borderBottomWidth: 0,
    },
    tableRow: {
        flexDirection: 'row',
        minHeight: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        alignItems: 'center',
    },
    tableHeader: {
        backgroundColor: '#F3F4F6',
        fontWeight: 'bold',
        color: '#111827',
    },
    tableCol: {
        paddingHorizontal: 5,
        paddingVertical: 3,
        fontSize: 8,
    },
    // Column widths
    colSite: { width: '15%' },
    colPart: { width: '15%' },
    colDesc: { width: '30%' },
    colLink: { width: '10%' },
    colAssets: { width: '30%' },

    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        fontSize: 8,
        color: '#9CA3AF',
        textAlign: 'center',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingTop: 10,
    }
});

export const SitePartReportPDF = ({ parts, assetMap }) => {
    // Group parts by Site for better organization? 
    // For now, simple list as per current filter is flexible.

    return (
        <Document>
            <Page size="A4" orientation="landscape" style={styles.page}>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Site Specific Parts Report</Text>
                    <Text style={styles.subtitle}>Generated on {new Date().toLocaleDateString()}</Text>
                </View>

                {/* Table Header */}
                <View style={[styles.tableRow, styles.tableHeader]}>
                    <Text style={[styles.tableCol, styles.colSite]}>Site Name</Text>
                    <Text style={[styles.tableCol, styles.colPart]}>Part Number</Text>
                    <Text style={[styles.tableCol, styles.colDesc]}>Description</Text>
                    <Text style={[styles.tableCol, styles.colLink]}>Link Type</Text>
                    <Text style={[styles.tableCol, styles.colAssets]}>Associated Assets</Text>
                </View>

                {/* Table Rows */}
                {parts.map((part, index) => {
                    const linkedAssetNames = (part.linkedAssetIds || [])
                        .map(id => {
                            const asset = assetMap[id];
                            return asset ? `${asset.name} (${asset.code})` : id;
                        })
                        .join(', ');

                    return (
                        <View key={index} style={styles.tableRow}>
                            <Text style={[styles.tableCol, styles.colSite]}>{part.siteName}</Text>
                            <Text style={[styles.tableCol, styles.colPart]}>{part.partNumber}</Text>
                            <Text style={[styles.tableCol, styles.colDesc]}>{part.description || '-'}</Text>
                            <Text style={[styles.tableCol, styles.colLink]}>
                                {part.internalPartType === 'none' ? 'Manual' : part.internalPartType}
                            </Text>
                            <Text style={[styles.tableCol, styles.colAssets]}>
                                {linkedAssetNames || '-'}
                            </Text>
                        </View>
                    );
                })}

                {/* Footer */}
                <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
                    `Page ${pageNumber} of ${totalPages} - Generated by AI Maintenance App`
                )} fixed />
            </Page>
        </Document>
    );
};
