import React from 'react';
import {
    Activity,
    Calendar,
    AlertTriangle,
    CheckCircle,
    Search,
    Scale,
    Settings,
    Clock,
    Database,
    Wrench,
    Edit,
    Plus,
    X,
    Printer,
    MapPin,
    FileText,
    Grid,
    ArrowLeft,
    Building,
    Upload,
    Trash,
    User,
    MessageCircle,
    Download,
    UploadCloud,
    ArrowUpDown,
    History,
    Undo,
    Briefcase,
    Phone,
    Mail,
    Contact,
    Save,
    Ban,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronDown,
    CheckSquare,
    FileSpreadsheet,
    Archive,
    Copy,
    Zap,
    Cpu,
    Orbit,
    Rocket,
    Maximize,
    Minimize,
    Maximize2,
    Minimize2
} from 'lucide-react';

// ==========================================
// ICONS
// ==========================================
export const Icons = {
    Activity: (props) => <Activity size={18} className="mr-1" {...props} />,
    Calendar: (props) => <Calendar size={18} className="mr-1" {...props} />,
    AlertTriangle: (props) => <AlertTriangle size={18} className="mr-1" {...props} />,
    CheckCircle: (props) => <CheckCircle size={18} className="mr-1" {...props} />,
    Search: (props) => <Search size={18} className="mr-1" {...props} />,
    Scale: (props) => <Scale size={18} className="mr-1" {...props} />,
    Settings: (props) => <Settings size={18} className="mr-1" {...props} />,
    Clock: (props) => <Clock size={18} className="mr-1" {...props} />,
    Database: (props) => <Database size={18} className="mr-1" {...props} />,
    Wrench: (props) => <Wrench size={18} className="mr-1" {...props} />,
    Edit: (props) => <Edit size={18} {...props} />,
    Plus: (props) => <Plus size={18} className="mr-2" {...props} />,
    X: (props) => <X size={18} {...props} />,
    Printer: (props) => <Printer size={18} {...props} />,
    MapPin: (props) => <MapPin size={18} className="mr-1" {...props} />,
    FileText: (props) => <FileText size={18} className="mr-1" {...props} />,
    Grid: (props) => <Grid size={18} className="mr-1" {...props} />,
    ArrowLeft: (props) => <ArrowLeft size={18} className="mr-1" {...props} />,
    Building: (props) => <Building size={18} {...props} />,
    Upload: (props) => <Upload size={18} className="mr-1" {...props} />,
    Trash: (props) => <Trash size={18} className="mr-1" {...props} />,
    User: (props) => <User size={18} className="mr-1" {...props} />,
    MessageCircle: (props) => <MessageCircle size={18} className="mr-1" {...props} />,
    Download: (props) => <Download size={18} className="mr-1" {...props} />,
    UploadCloud: (props) => <UploadCloud size={18} className="mr-1" {...props} />,
    Sort: (props) => <ArrowUpDown size={18} className="mr-1" {...props} />,
    History: (props) => <History size={18} className="mr-1" {...props} />,
    Undo: (props) => <Undo size={18} {...props} />,
    Briefcase: (props) => <Briefcase size={18} className="mr-1" {...props} />,
    Phone: (props) => <Phone size={18} className="mr-1" {...props} />,
    Mail: (props) => <Mail size={18} className="mr-1" {...props} />,
    Contact: (props) => <Contact size={18} {...props} />,
    Save: (props) => <Save size={18} {...props} />,
    Cancel: (props) => <Ban size={18} {...props} />,
    ChevronLeft: (props) => <ChevronLeft size={18} {...props} />,
    ChevronRight: (props) => <ChevronRight size={18} {...props} />,
    ChevronUp: (props) => <ChevronUp size={18} {...props} />,
    ChevronDown: (props) => <ChevronDown size={18} {...props} />,
    SortAsc: (props) => <ChevronUp size={14} className="ml-1" {...props} />,
    SortDesc: (props) => <ChevronDown size={14} className="ml-1" {...props} />,
    CheckSquare: (props) => <CheckSquare size={18} {...props} />,
    FileCsv: (props) => <FileSpreadsheet size={18} {...props} />,
    Archive: (props) => <Archive size={18} {...props} />,
    Copy: (props) => <Copy size={18} {...props} />,
    Zap: (props) => <Zap size={18} {...props} />,
    Cpu: (props) => <Cpu size={18} {...props} />,
    Orbit: (props) => <Orbit size={18} {...props} />,
    Rocket: (props) => <Rocket size={18} {...props} />,
    Maximize: (props) => <Maximize size={18} {...props} />,
    Minimize: (props) => <Minimize size={18} {...props} />,
    Maximize2: (props) => <Maximize2 size={18} {...props} />,
    Minimize2: (props) => <Minimize2 size={18} {...props} />,
};
